---
- name: installation serveur web Apache2
  hosts: debian
#  remote_user: root

  tasks:
    - name: Installation de apache2
      package:
        name: apache2
        state: latest

    - name: Modifier le port d'écoute 80
      lineinfile:
         path: /etc/apache2/ports.conf
         regex: '^Listen'
         line: Listen 8080
      notify: reload_apache
      register: result
    
    - name: Consultation
      debug:
        var: result

    - name: Relancer le service apache2
      systemd:
        state: reloaded
        name: apache2
      when: result.changed == true

    - name: Whoami
      shell: whoami
      changed_when: false